from typing import Literal


AGENT_EVENT_TYPE = Literal[
    "workflow.trace",
    "workflow.node_entered",
    "workflow.intent_routed",
    "workflow.coding_prepared",
    "workflow.unknown_intent_completed",
    "workflow.node_exception",
    "chat.started",
    "chat.response_ready",
    "chat.response_failed",
    "chat.completed",
    "chat.failed",
    "chat.message",
    "tool.applied",
    "tool.failed",
    "tool.skipped",
    "run.created",
    "run.create_failed",
    "run.snapshot_ready",
    "run.snapshot_in_progress",
    "run.snapshot_terminal",
    "run.snapshot_failed",
    "run.control_completed",
    "run.control_failed",
    "run.queued",
    "run.started",
    "run.repair_started",
    "run.finished",
    "run.failed",
    "run.cancelled",
    "roleplay.emitted",
    "diagnostics.route_selected",
    "diagnostics.coding_path_selected",
    "character.quip",
    "character.expression",
    "character.motion",
    "status.updated",
    "system.error",
]

AGENT_EVENT_SOURCE = Literal[
    "workflow",
    "chat",
    "run",
    "tool",
    "character",
    "roleplay",
    "diagnostics",
    "system",
]

AGENT_EVENT_STAGE = Literal[
    "routing",
    "chat",
    "coding",
    "tools",
    "run_create",
    "run_read",
    "run_control",
    "run",
    "repair",
    "fallback",
    "roleplay",
    "diagnostics",
    "unknown",
    "system",
]
